# Generated by Django 4.1.7 on 2023-03-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(db_column='Booking_ID', primary_key=True, serialize=False)),
                ('pickup', models.CharField(db_column='Pickup', max_length=50)),
                ('dropoff', models.CharField(db_column='Dropoff', max_length=50)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discountoffers',
            fields=[
                ('discountid', models.AutoField(db_column='DiscountID', primary_key=True, serialize=False)),
                ('discount_detail', models.CharField(blank=True, db_column='Discount_Detail', max_length=50, null=True)),
                ('discount_percentage', models.IntegerField(db_column='Discount_Percentage')),
            ],
            options={
                'db_table': 'discountoffers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(db_column='Driver_ID', primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('e_mail', models.CharField(db_column='E_mail', max_length=100, unique=True)),
                ('driverpassword', models.CharField(db_column='DriverPassword', max_length=50)),
                ('driver_rating', models.IntegerField(db_column='Driver_rating')),
                ('dr_status', models.CharField(db_column='Dr_Status', max_length=8)),
                ('dob', models.DateField(db_column='DOB')),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('payment_amount', models.IntegerField(db_column='Payment_Amount')),
                ('payment_method', models.CharField(db_column='Payment_Method', max_length=11)),
                ('payment_status', models.CharField(db_column='Payment_Status', max_length=7)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('rideid', models.AutoField(db_column='RideID', primary_key=True, serialize=False)),
                ('tracking', models.CharField(blank=True, db_column='Tracking', max_length=50, null=True)),
                ('r_type', models.CharField(db_column='R_Type', max_length=4)),
            ],
            options={
                'db_table': 'ride',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RideeaseBooking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pickup', models.CharField(max_length=100)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('dropoff', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rideease_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RideeaseDriver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rideease_driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('tracking_id', models.AutoField(db_column='Tracking_ID', primary_key=True, serialize=False)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('user_status', models.CharField(db_column='User_Status', max_length=6)),
                ('e_mail', models.CharField(db_column='E_mail', max_length=100, unique=True)),
                ('userpassword', models.CharField(db_column='UserPassword', max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_column='Vehicle_ID', primary_key=True, serialize=False)),
                ('license_platenumber', models.CharField(db_column='License_Platenumber', max_length=20, unique=True)),
                ('model', models.CharField(db_column='Model', max_length=50)),
                ('make', models.CharField(db_column='Make', max_length=50)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivesfor',
            fields=[
                ('drivid', models.OneToOneField(db_column='DrivID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='RideEase.driver')),
                ('tim', models.DateTimeField(blank=True, db_column='Tim', null=True, unique=True)),
                ('distance', models.FloatField(db_column='Distance')),
            ],
            options={
                'db_table': 'drivesfor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('user', models.OneToOneField(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='RideEase.users')),
                ('phone_number1', models.CharField(db_column='Phone_number1', max_length=20)),
                ('phone_number2', models.CharField(db_column='Phone_number2', max_length=20)),
            ],
            options={
                'db_table': 'user_phone',
                'managed': False,
            },
        ),
    ]
